services:
  postgres:
    image: postgres:17
    container_name: cyrus-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: cyrus
      POSTGRES_USER: cyrus
      POSTGRES_PASSWORD: cyrus_password
    ports:
      - "5438:5432"

    volumes:
      - cyrus_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cyrus -d cyrus"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  cyrus_postgres_data: