from enum import Enum


class TransactionType(str, Enum):
    CUSTOMER_PAYMENT = "CUSTOMER_PAYMENT"
    PAYOUT = "PAYOUT"
    REVERSAL = "REVERSAL"
    ADJUSTMENT = "ADJUSTMENT"


class TransactionStatus(str, Enum):
    PENDING = "PENDING"
    SUCCESSFUL = "SUCCESSFUL"
    FAILED = "FAILED"
    REVERSED = "REVERSED"


class MatchStatus(str, Enum):
    MATCHED = "MATCHED"
    UNMATCHED = "UNMATCHED"
    DISCREPANCY = "DISCREPANCY"
    ORPHANED = "ORPHANED"
    MANUAL_REVIEW = "MANUAL_REVIEW"


class CustomerStatus(str, Enum):
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    CLOSED = "CLOSED"


class KycTier(str, Enum):
    TIER_1 = "TIER_1"
    TIER_2 = "TIER_2"
    TIER_3 = "TIER_3"


class PaymentEventType(str, Enum):
    PAYMENT_SUCCESS = "PAYMENT_SUCCESS"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    PAYMENT_REVERSED = "PAYMENT_REVERSED"
    PAYOUT_SUCCESS = "PAYOUT_SUCCESS"
    PAYOUT_FAILED = "PAYOUT_FAILED"
    PAYOUT_REFUND = "PAYOUT_REFUND"
    UNKNOWN = "UNKNOWN"


class PaymentEventStatus(str, Enum):
    RECEIVED = "RECEIVED"
    PROCESSED = "PROCESSED"
    IGNORED = "IGNORED"
    PROCESSED_DUPLICATE = "PROCESSED_DUPLICATE"
    FAILED = "FAILED"
    REATTRIBUTED = "REATTRIBUTED"


class ReconciliationFailureReason(str, Enum):
    UNKNOWN_VIRTUAL_ACCOUNT = "UNKNOWN_VIRTUAL_ACCOUNT"
    INACTIVE_CUSTOMER = "INACTIVE_CUSTOMER"
    NON_CREDIT_EVENT = "NON_CREDIT_EVENT"
    DUPLICATE = "DUPLICATE"
    SIGNATURE_MISMATCH = "SIGNATURE_MISMATCH"
    AMOUNT_MISMATCH = "AMOUNT_MISMATCH"
    PROVIDER_UNCONFIRMED = "PROVIDER_UNCONFIRMED"
