-- Baseline migration: captures the schema as generated by Hibernate ddl-auto=update up to this
-- point. From here on, schema changes are hand-written Flyway migrations (ddl-auto is now
-- validate-only). JobRunr's own tables (jobrunr_*) are NOT included here — JobRunr manages its
-- own schema via its own internal migration mechanism, independent of Flyway.

create table merchants
(
    id                       uuid                        not null
        primary key,
    created_at               timestamp(6) with time zone not null,
    updated_at               timestamp(6) with time zone,
    bank_verification_number varchar(255),
    business_email           varchar(255)                not null
        constraint ukgbiuloaq77ox1xunocq0rs51l
            unique,
    business_name            varchar(255)                not null,
    business_type            varchar(255),
    password_hash            varchar(255)                not null,
    phone                    varchar(255),
    photo_url                varchar(255),
    status                   varchar(255)                not null
        constraint merchants_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING_VERIFICATION'::character varying, 'ACTIVE'::character varying, 'SUSPENDED'::character varying, 'DISABLED'::character varying])::text[])),
    virtual_account_limit    integer                     not null,
    url                      varchar(255),
    encrypted_secret         varchar(255)
);

create table api_keys
(
    id           uuid                        not null
        primary key,
    created_at   timestamp(6) with time zone not null,
    updated_at   timestamp(6) with time zone,
    expires_at   timestamp(6) with time zone,
    key_hash     varchar(255)                not null
        constraint ukcwrf6urvb9lnvuli1giq8t2k9
            unique,
    last_used_at timestamp(6) with time zone,
    prefix       varchar(100)                not null,
    revoked_at   timestamp(6) with time zone,
    status       varchar(255)                not null
        constraint api_keys_status_check
            check ((status)::text = ANY
                   ((ARRAY ['ACTIVE'::character varying, 'REVOKED'::character varying, 'EXPIRED'::character varying])::text[])),
    merchant_id  uuid                        not null
        constraint fk7v50sul4eg52php1vyyrli9xu
            references merchants
);

create index idx_api_key_hash
    on api_keys (key_hash);

create table beneficiaries
(
    id                      uuid                        not null
        primary key,
    created_at              timestamp(6) with time zone not null,
    updated_at              timestamp(6) with time zone,
    account_name            varchar(255)                not null,
    account_number          varchar(10)                 not null,
    bank_code               varchar(10)                 not null,
    bank_name               varchar(255)                not null,
    nickname                varchar(255)                not null,
    provider_beneficiary_id varchar(255),
    merchant_id             uuid                        not null
        constraint fkpi2yw94s44dou3rgcijkug6ep
            references merchants
);

create index idx_beneficiary_merchant
    on beneficiaries (merchant_id);

create index idx_beneficiary_account
    on beneficiaries (merchant_id, account_number);

create table merchant_customers
(
    id                   uuid                        not null
        primary key,
    created_at           timestamp(6) with time zone not null,
    updated_at           timestamp(6) with time zone,
    email                varchar(255),
    external_customer_id varchar(255)                not null,
    first_name           varchar(255)                not null,
    kyc_tier             varchar(255)                not null
        constraint merchant_customers_kyc_tier_check
            check ((kyc_tier)::text = ANY
                   ((ARRAY ['TIER_1'::character varying, 'TIER_2'::character varying, 'TIER_3'::character varying])::text[])),
    last_name            varchar(255),
    metadata             oid,
    phone_number         varchar(255),
    status               varchar(255)                not null
        constraint merchant_customers_status_check
            check ((status)::text = ANY
                   ((ARRAY ['ACTIVE'::character varying, 'SUSPENDED'::character varying, 'CLOSED'::character varying])::text[])),
    merchant_id          uuid                        not null
        constraint fknnu2d7uss6x9vp4orhf8tsm8j
            references merchants,
    constraint uk_merchant_customer_external_id
        unique (merchant_id, external_customer_id)
);

create table tokens
(
    id          uuid                        not null
        primary key,
    created_at  timestamp(6) with time zone not null,
    updated_at  timestamp(6) with time zone,
    expires_at  timestamp(6) with time zone not null,
    token       varchar(255)                not null
        constraint ukna3v9f8s7ucnj16tylrs822qj
            unique,
    type        varchar(255)                not null
        constraint tokens_type_check
            check ((type)::text = ANY
                   ((ARRAY ['EMAIL_VERIFICATION'::character varying, 'PASSWORD_RESET'::character varying])::text[])),
    used        boolean                     not null,
    merchant_id uuid                        not null
        constraint fke886x6c824ml237qivps4vmd8
            references merchants
);

create table virtual_accounts
(
    id                   uuid                        not null
        primary key,
    created_at           timestamp(6) with time zone not null,
    updated_at           timestamp(6) with time zone,
    account_name         varchar(255),
    account_number       varchar(255)                not null
        constraint uk6g99wb7iuqo6bpxvpixnfoh7w
            unique,
    bank_name            varchar(255),
    currency             varchar(255)                not null
        constraint virtual_accounts_currency_check
            check ((currency)::text = 'NGN'::text),
    provider_reference   varchar(255),
    status               varchar(255)                not null
        constraint virtual_accounts_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'ACTIVE'::character varying, 'SUSPENDED'::character varying, 'CLOSED'::character varying])::text[])),
    merchant_customer_id uuid                        not null
        constraint ukjpqnahdsy34opuf2h2begcfc4
            unique
        constraint fk1icfsd705xmuwsqrxs79vi2tv
            references merchant_customers
);

create table nomba_payment_events
(
    id                 uuid                        not null
        primary key,
    created_at         timestamp(6) with time zone not null,
    updated_at         timestamp(6) with time zone,
    account_number     varchar(255),
    amount             numeric(38)                 not null,
    customer_reference varchar(255),
    event_type         varchar(255)                not null
        constraint nomba_payment_events_event_type_check
            check ((event_type)::text = ANY
                   ((ARRAY ['PAYMENT_SUCCESS'::character varying, 'PAYMENT_FAILED'::character varying, 'PAYMENT_REVERSED'::character varying, 'UNKNOWN'::character varying])::text[])),
    failure_reason     varchar(255)
        constraint nomba_payment_events_failure_reason_check
            check ((failure_reason)::text = ANY
                   ((ARRAY ['UNKNOWN_VIRTUAL_ACCOUNT'::character varying, 'INACTIVE_CUSTOMER'::character varying, 'NON_CREDIT_EVENT'::character varying, 'DUPLICATE'::character varying, 'SIGNATURE_MISMATCH'::character varying, 'AMOUNT_MISMATCH'::character varying, 'PROVIDER_UNCONFIRMED'::character varying])::text[])),
    fee                numeric(38),
    narration          varchar(500),
    provider_wallet_id varchar(255),
    raw_payload        oid,
    request_id         varchar(255)                not null
        constraint uk_npe_request_id
            unique,
    session_id         varchar(255),
    signature          varchar(500),
    status             varchar(255)                not null
        constraint nomba_payment_events_status_check
            check ((status)::text = ANY
                   ((ARRAY ['RECEIVED'::character varying, 'PROCESSED'::character varying, 'IGNORED'::character varying, 'PROCESSED_DUPLICATE'::character varying, 'FAILED'::character varying, 'REATTRIBUTED'::character varying])::text[])),
    status_details     varchar(255),
    transaction_id     varchar(255),
    merchant_id        uuid
        constraint fkg1j3h564rakhqfhfwwnkl7uoc
            references merchants,
    virtual_account_id uuid
        constraint fkoacxej6m2njnvn7ys0mvyo8qk
            references virtual_accounts
);

create index idx_npe_session_id
    on nomba_payment_events (session_id);

create index idx_npe_account_number
    on nomba_payment_events (account_number);

create index idx_npe_status
    on nomba_payment_events (status);

create table transactions
(
    id                      uuid                        not null
        primary key,
    created_at              timestamp(6) with time zone not null,
    updated_at              timestamp(6) with time zone,
    amount                  numeric(38)                 not null,
    currency                varchar(255)                not null
        constraint transactions_currency_check
            check ((currency)::text = 'NGN'::text),
    fee                     numeric(38),
    last_reconciled_at      timestamp(6) with time zone,
    match_status            varchar(255)                not null
        constraint transactions_match_status_check
            check ((match_status)::text = ANY
                   ((ARRAY ['MATCHED'::character varying, 'UNMATCHED'::character varying, 'DISCREPANCY'::character varying, 'ORPHANED'::character varying, 'MANUAL_REVIEW'::character varying])::text[])),
    match_status_details    varchar(255),
    narration               varchar(500),
    payer_account_number    varchar(255),
    payer_bank              varchar(255),
    payer_name              varchar(255),
    provider_transaction_id varchar(255)
        constraint uk_transaction_provider_tx_id
            unique,
    raw_payload             text,
    received_at             timestamp(6) with time zone,
    reconciliation_attempts integer                     not null,
    reference               varchar(255)                not null
        constraint uk_transaction_reference
            unique,
    request_id              varchar(255),
    session_id              varchar(255),
    status                  varchar(255)                not null
        constraint transactions_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'SUCCESSFUL'::character varying, 'FAILED'::character varying, 'REVERSED'::character varying])::text[])),
    type                    varchar(255)                not null
        constraint transactions_type_check
            check ((type)::text = ANY
                   ((ARRAY ['CUSTOMER_PAYMENT'::character varying, 'PAYOUT'::character varying, 'REVERSAL'::character varying, 'ADJUSTMENT'::character varying])::text[])),
    customer_id             uuid
        constraint fkj0w1ygr4tcvrv85e76rlf7pvq
            references merchant_customers,
    merchant_id             uuid                        not null
        constraint fkosju61fahf0o80fnd5p59jch5
            references merchants,
    payment_event_id        uuid
        constraint ukdhm8a82ndniyleskcspsel4y6
            unique
        constraint fkbpwdkdaaacg7i357ltso23l7o
            references nomba_payment_events,
    virtual_account_id      uuid
        constraint fkeptdhm6d3v9782vjiuvu6akeh
            references virtual_accounts,
    platform_fee_kobo       numeric(38),
    version                 bigint                      not null
);

create table merchant_webhook_events
(
    id                 uuid                        not null
        primary key,
    created_at         timestamp(6) with time zone not null,
    updated_at         timestamp(6) with time zone,
    attempts           integer                     not null,
    delivered_at       timestamp(6) with time zone,
    event_type         varchar(255),
    last_error         varchar(255),
    last_response_code integer,
    next_retry_at      timestamp(6) with time zone,
    payload            text,
    status             varchar(255)
        constraint merchant_webhook_events_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'DELIVERED'::character varying, 'RETRYING'::character varying, 'FAILED'::character varying])::text[])),
    webhook_url        varchar(255),
    merchant_id        uuid
        constraint fkpb55ojcwn2ta8ia287qp5o8ul
            references merchants,
    transaction_id     uuid
        constraint uk3pecuexhyhvpd3hd5hoxxxmw3
            unique
        constraint fkto2x86qvj4srdrtqd1r425rb9
            references transactions,
    constraint uk_webhook_transaction_event
        unique (transaction_id, event_type)
);

create table payouts
(
    id                 uuid                        not null
        primary key,
    created_at         timestamp(6) with time zone not null,
    updated_at         timestamp(6) with time zone,
    amount             numeric(38)                 not null,
    failure_reason     varchar(255),
    fee                numeric(38),
    narration          varchar(500),
    provider_reference varchar(255),
    reference          varchar(255)                not null
        constraint uk_payout_reference
            unique,
    status             varchar(255)                not null
        constraint payouts_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'PROCESSING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying])::text[])),
    beneficiary_id     uuid                        not null
        constraint fkl2uk6k1gc6ojtf0a1f8hwjxc0
            references beneficiaries,
    merchant_id        uuid                        not null
        constraint fk8licm05wd92o5pxmq4mshghn2
            references merchants,
    transaction_id     uuid
        constraint ukftic5wqgihlqkwix6jr30tc81
            unique
        constraint fkph49ybw0nn66lg9ow4un6psv2
            references transactions
);

create index idx_payout_merchant
    on payouts (merchant_id);

create index idx_payout_status
    on payouts (status);

create table wallets
(
    id                uuid                        not null
        primary key,
    created_at        timestamp(6) with time zone not null,
    updated_at        timestamp(6) with time zone,
    available_balance numeric(38)                 not null,
    version           bigint                      not null,
    merchant_id       uuid                        not null
        constraint uk5u9ef21m9mckkvv4gi6qktys6
            unique
        constraint fkipfqpb35qo27pksmsem027mam
            references merchants
);

create table ledger_entries
(
    id             uuid                        not null
        primary key,
    created_at     timestamp(6) with time zone not null,
    updated_at     timestamp(6) with time zone,
    amount         numeric(38)                 not null,
    description    varchar(500),
    type           varchar(255)                not null
        constraint ledger_entries_type_check
            check ((type)::text = ANY
                   ((ARRAY ['MERCHANT_WALLET_CREDIT'::character varying, 'MERCHANT_WALLET_DEBIT'::character varying, 'PROVIDER_FEE'::character varying, 'PLATFORM_FEE'::character varying, 'PAYOUT'::character varying, 'PAYOUT_FEE'::character varying, 'REVERSAL'::character varying, 'ADJUSTMENT'::character varying])::text[])),
    transaction_id uuid                        not null
        constraint fkgwcsld4m3g325l66qro45i14x
            references transactions,
    wallet_id      uuid                        not null
        constraint fkcfwn04lfp5eyco3vbjc3729ib
            references wallets
);

create index idx_ledger_transaction
    on ledger_entries (transaction_id);

create index idx_ledger_wallet
    on ledger_entries (wallet_id);

create index idx_ledger_type
    on ledger_entries (type);

create table webhook_deliveries
(
    id               uuid                        not null
        primary key,
    created_at       timestamp(6) with time zone not null,
    updated_at       timestamp(6) with time zone,
    attempt_number   integer                     not null,
    failure_reason   varchar(1000),
    response_body    oid,
    response_status  integer,
    webhook_event_id uuid                        not null
        constraint fkduvppi74l1ty4bxn0n0o8vnyn
            references merchant_webhook_events
);

create index idx_delivery_event
    on webhook_deliveries (webhook_event_id);
