name: CD - Deploy to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - pom.xml
      - Dockerfile
      - mvnw
      - .mvn/**
      - src/main/resources/application*.yml
      - .github/workflows/**
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

env:
  GCP_REGION: us-central1
  GCP_PROJECT_ID: nombacyrus

  GAR_REPOSITORY: cyrus
  SERVICE_NAME: cyrus-api

  IMAGE_NAME: cyrus-api
jobs:
  deploy:
    name: Docker Build, Push & Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate version info
        id: version
        run: |
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
          VERSION=${VERSION#v}
          SHA=$(git rev-parse HEAD)

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "sha=$SHA" >> $GITHUB_OUTPUT
      #
      # Authenticate GitHub -> GCP
      #
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: |
          gcloud auth configure-docker \
          us-central1-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        run: |

          IMAGE="us-central1-docker.pkg.dev/${GCP_PROJECT_ID}/${GAR_REPOSITORY}/${IMAGE_NAME}"

          docker buildx build \
            --platform linux/amd64 \
            -t $IMAGE:${{ steps.version.outputs.sha }} \
            -t $IMAGE:latest \
            --push \
            .
      - name: Deploy Cloud Run
        run: |
          IMAGE="us-central1-docker.pkg.dev/${GCP_PROJECT_ID}/${GAR_REPOSITORY}/${IMAGE_NAME}"
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE:${{ steps.version.outputs.sha }} \
            --region $GCP_REGION \
            --platform managed \
            --service-account cyrus-api-runtime@nombacyrus.iam.gserviceaccount.com \
            --allow-unauthenticated \
            --memory 512Mi \
            --cpu 1 \
            --min-instances 0 \
            --max-instances 3 \
            --timeout 60

      - name: Show URL
        run: |
          gcloud run services describe $SERVICE_NAME \
            --region=$GCP_REGION \
            --format='value(status.url)'
          
          
